#!/bin/bash
#Set up script for cscheme

USERNAME="$(whoami)"

if [ ! -f ~/.config/cscheme]; then
	mkdir ~/.config/cscheme
	mkdir ~/.config/cscheme/schemes
	touch ~/.config/cscheme/conf
	echo "USERNAME=$USERNAME" >> ~/.config/cscheme/conf
	echo "SCHEMEDIR=/home/$USERNAME/.config/cscheme/" >> ~/.config/cscheme/conf
fi



